AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 200

Metrics/ParameterLists:
  Enabled: false

Layout/LineLength:
  Max: 140

Naming/VariableNumber:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

# Style

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RedundantSelfAssignment:
  Enabled: false

Style/FileWrite:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# RSpec

# RSpec/IndexedLet:
#   Enabled: false

# RSpec/AnyInstance:
#   Enabled: false

# RSpec/HookArgument:
#   Enabled: false

# RSpec/ExampleLength:
#   Max: 25

# RSpec/LetSetup:
#   Enabled: false

# RSpec/NestedGroups:
#   Enabled: false

# RSpec/MessageSpies:
#   Enabled: false

# RSpec/MultipleExpectations:
#   Enabled: false

# RSpec/MultipleMemoizedHelpers:
#   Enabled: false
